language: go

go:
  - 1.11.x

services:
  - docker

before_install:
  - go get -v ./...

script:
  - make test

after_success:
  - make build
  - docker build -t sysfiller/simpleapi:$TRAVIS_BUILD_NUMBER .
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker push sysfiller/simpleapi:$TRAVIS_BUILD_NUMBER